title: A Mohamed Ashiq
logo: /assets/img/profile-pic.png

description: An Analyst Enthusiast
#show_downloads: False

Contact: + (65) 85140207 

Email: mohamed.ashiq.adv@gmail.com

LinkedIn: https://www.linkedin.com/in/mdashiq99/

theme: jekyll-theme-minimal
